spring:
  application:
    name: bookstore
  datasource:
    url: jdbc:h2:mem:bookstore
    driver-class-name: org.h2.Driver
#    TODO: Username & Password should be stored securely
    username: sa
    password: sa
  jpa:
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
  profiles:
    active: dev

jwt:
  secret: secure-string
  expiration: 3600000

logging:
  level:
    org:
      springframework:
        security: DEBUG


